# Generated by Django 3.2 on 2021-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='title',
        ),
        migrations.AddField(
            model_name='slot',
            name='column',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='row',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
