# Generated by Django 3.2 on 2021-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0004_rename_slot_row_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column_slot',
            name='column',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='row_slot',
            name='row',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
