# Generated by Django 3.2 on 2021-04-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0005_auto_20210413_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Row_Slot',
            new_name='Slot',
        ),
    ]
