# Generated by Django 3.2 on 2021-04-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0006_rename_row_slot_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='column',
        ),
        migrations.AddField(
            model_name='slot',
            name='column_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lot_info.column_slot'),
        ),
    ]
