# Generated by Django 3.2 on 2021-04-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0008_auto_20210413_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='column_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lot_info.column_slot'),
        ),
    ]
