# Generated by Django 3.2 on 2021-04-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0009_alter_slot_column_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='column_id',
            new_name='column_id_id',
        ),
    ]
