# Generated by Django 3.2 on 2021-04-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0010_rename_column_id_slot_column_id_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='column_id_id',
        ),
        migrations.AddField(
            model_name='slot',
            name='column_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lot_info.column_slot'),
        ),
    ]
