# Generated by Django 3.2 on 2021-04-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0012_auto_20210413_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column_slot',
            name='is_filled',
        ),
    ]
