# Generated by Django 3.2 on 2021-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_info', '0013_remove_column_slot_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
